name: Build and Push Docker Images

on:
  push:
    branches:
      - backend # backend 브랜치에 푸시될 때 실행

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1. DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Checkout 코드
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3. MySQL Docker 이미지 빌드 및 푸시
      - name: Build MySQL Docker image
        working-directory: db # db 폴더로 이동
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/testdockerdb .

      - name: Push MySQL Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/testdockerdb

      # 4. Backend Docker 이미지 빌드 및 푸시
      - name: Build Backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/testdockerbackend .
      - name: Push Backend Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/testdockerbackend

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull and run
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ "$(sudo docker ps -a -q -f name=testdockerdb)" ]; then
              sudo docker rm -f testdockerdb
            fi
            if [ "$(sudo docker ps -a -q -f name=testdockerbackend)" ]; then
              sudo docker rm -f testdockerbackend
            fi
            if [ "$(sudo docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/testdockerdb)" ]; then
              sudo docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/testdockerdb
            fi
            if [ "$(sudo docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/testdockerbackend)" ]; then
              sudo docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/testdockerbackend
            fi
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/testdockerdb
            sudo docker run -d -p 3308:3306 --name testdockerdb -v testdockerdb_volume:/var/lib/mysql ${{ secrets.DOCKERHUB_USERNAME }}/testdockerdb
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/testdockerbackend
            sudo docker run -d -p 8000:8080 --name testdockerbackend ${{ secrets.DOCKERHUB_USERNAME }}/testdockerbackend